
GET http://localhost:3000/users

### create user
POST http://localhost:3000/users
Content-Type: application/json 

{
    "username":"poorna9",
    "email":"example9@gmail.com"
}

### get user by id , name , user
GET http://localhost:3000/users/example5@gmail.com


### modify user 
PATCH  http://localhost:3000/users/example1@gmail.com
Content-Type: application/json

{"email":"example7@gmail.com"}

### delete user
DELETE  http://localhost:3000/users/poorna



###
GET http://localhost:3000/ndnvf